apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrk
  template:
    metadata:
      labels:
        app: wrk
    spec:
      containers:
        - name: wrk
          image: shivamhire123123/wrk2:latest
